# Generated by Django 4.1.5 on 2023-01-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='название')),
                ('language', models.CharField(blank=True, max_length=50, verbose_name='язык программирования')),
            ],
        ),
    ]
